---
- name: Download mssql repo file
  get_url:
    url: https://packages.microsoft.com/config/rhel/7/mssql-server-2017.repo
    dest: /etc/yum.repos.d/mssql-server.repo
    mode: '0644'

- name: Install MSSQL server 2017
  yum:
    name: mssql-server
    state: present
    update_cache: yes

- name: Setup of MSSQL server
  shell: /opt/mssql/bin/mssql-conf -n setup
  environment:
    MSSQL_SA_PASSWORD: "Password1!"
    MSSQL_PID: "express"
    SQL_ENABLE_AGENT: "y"
    