---
- name: Install python deps for pip install
  yum:
    name:
      - python2-pip
      - python-virtualenv
      - python-setuptools
    state: present

- name: Install pexpect using pip
  pip:
    name: pexpect

- name: Download mssql repo file
  get_url:
    url: https://packages.microsoft.com/config/rhel/7/mssql-server-2017-gdr.repo
    dest: /etc/yum.repos.d/mssql-server.repo
    mode: '0644'

- name: Install MSSQL server 2017
  yum:
    name: mssql-server
    state: present
    update_cache: yes

- name: Setup of MSSQL server
  shell: /opt/mssql/bin/mssql-conf -n setup
  environment:
    MSSQL_SA_PASSWORD: "{{ sa_passwd }}"
    MSSQL_PID: "{{ db_edition }}"
    SQL_ENABLE_AGENT: "Y"
    ACCEPT_EULA: "Y"
    SQL_INSTALL_USER: "jiradbuser"
    SQL_INSTALL_USER_PASSWORD: "{{ sa_passwd }}"

- name: Stop mssql so we can set collation
  systemd:
    name: mssql-server
    state: stopped

- name: Case insensitive password string match
  expect:
    command: /opt/mssql/bin/mssql-conf set-collation
    timeout: null
    responses:
      (?i)collation: "SQL_Latin1_General_CP437_CI_AI"

- name: Make sure mssql runs under systemd
  systemd:
    name: mssql-server
    state: started
    enabled: yes

- firewalld:
    port: 1433/tcp
    permanent: yes
    immediate: yes
    state: enabled
