---
- name: Install fonts for Web UI
  yum:
    name: fontconfig
    state: present

- name: Download jira install media
  get_url:
    url: http://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-{{ jira_version }}-x64.bin
    dest: /tmp/atlassian-jira-software-{{ jira_version }}-x64.bin
    mode: '0777'

- name: Copy response file for installer
  copy:
    src: response.varfile
    dest: /tmp/response.varfile

- name: Install jira using the response file
  shell: /tmp/atlassian-jira-software-{{ jira_version }}-x64.bin -q -varfile /tmp/response.varfile
  args:
    executable: /bin/bash

- name: Kill the running jira instance
  shell: /opt/atlassian/jira/bin/stop-jira.sh

- name: Copy service file for jira
  copy:
    src: jira.service
    dest: /etc/systemd/system/jira.service
    mode: '0644'
    owner: root
    group: root

- name: Force systemd to learn of new service
  systemd:
    daemon_reload: yes

- name: Make sure jira runs under systemd
  systemd:
    name: jira
    state: started
    enabled: yes

- firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled
